# Generated by Django 5.1.6 on 2025-02-24 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='', max_length=200, unique=True)),
                ('title', models.CharField(max_length=60, verbose_name='Название')),
                ('image', models.ImageField(upload_to='card_images/%Y-%m-%d/', verbose_name='Картинка')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('information', models.TextField(default='', verbose_name='Информация')),
            ],
        ),
    ]
