# Generated by Django 5.1.6 on 2025-02-25 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mebel1', '0003_category_alter_comment_name_alter_comment_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='price',
            field=models.FloatField(verbose_name='Цена от'),
        ),
    ]
