# Generated by Django 5.1.6 on 2025-02-25 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mebel1', '0004_alter_card_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='price',
            field=models.FloatField(verbose_name='Цена'),
        ),
    ]
